# Generated by Django 5.0.6 on 2024-05-28 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="added_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="films_added",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="want_to_watch",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="films_to_watch",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="watched",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="films_watched",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
