# Generated by Django 5.0.6 on 2024-05-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0002_film_added_by_film_want_to_watch_film_watched"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="film",
            name="rating",
        ),
    ]
