# Generated by Django 5.0.6 on 2024-06-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0003_remove_film_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="category",
            field=models.CharField(
                choices=[
                    ("DR", "Drama"),
                    ("HR", "Horror"),
                    ("TH", "Thriller"),
                    ("CM", "Comedy"),
                ],
                default="DR",
                max_length=2,
            ),
        ),
    ]
