# Generated by Django 5.0.6 on 2024-06-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0004_film_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="category",
            field=models.CharField(
                choices=[
                    ("Dramat", "Drama"),
                    ("Horror", "Horror"),
                    ("Thriller", "Thriller"),
                    ("Komedia", "Comedy"),
                ],
                default="Dramat",
                max_length=8,
            ),
        ),
    ]
