# Generated by Django 5.0.6 on 2024-05-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discordlogin", "0002_film"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Film",
        ),
    ]
