# Generated by Django 5.0.6 on 2024-05-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discordlogin", "0005_alter_discorduser_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="discorduser",
            name="discord_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
